server:
  port: 8082

spring:
  application:
    name: craft-gateway-service
  cloud:
    gateway:
      routes:
        - id: sales-service
          uri: http://${SALES_HOST:localhost}:${SALES_PORT:8085}
          predicates:
            - Path=/api/sales/**
          filters:
            - StripPrefix=2
        - id: finance-service
          uri: http://${FINANCE_HOST:localhost}:${FINANCE_PORT:8084}
          predicates:
            - Path=/api/finance/**
          filters:
            - StripPrefix=2
        - id: identity-service
          uri: http://${IDENTITY_HOST:localhost}:${IDENTITY_PORT:8083}
          predicates:
            - Path=/api/auth/**
        - id: inventory-service
          uri: http://${INVENTORY_HOST:localhost}:${INVENTORY_PORT:8080}
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=2
        - id: production-service
          uri: http://${PRODUCTION_HOST:localhost}:${PRODUCTION_PORT:8081}
          predicates:
            - Path=/api/production/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: health,info
